# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'whole_optic_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1824, 922)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camera = QtWidgets.QFrame(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(10, 80, 1091, 801))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.camera.setFont(font)
        self.camera.setFrameShape(QtWidgets.QFrame.Box)
        self.camera.setObjectName("camera")
        self.graphicsView = Custom_pyqtgraph_widget(self.camera)
        self.graphicsView.setGeometry(QtCore.QRect(20, 40, 1041, 651))
        self.graphicsView.setObjectName("graphicsView")
        self.replay_button = QtWidgets.QPushButton(self.camera)
        self.replay_button.setGeometry(QtCore.QRect(140, 10, 80, 21))
        self.replay_button.setObjectName("replay_button")
        self.stream_button = QtWidgets.QPushButton(self.camera)
        self.stream_button.setGeometry(QtCore.QRect(270, 10, 80, 21))
        self.stream_button.setObjectName("stream_button")
        self.exposure_time_label = QtWidgets.QLabel(self.camera)
        self.exposure_time_label.setGeometry(QtCore.QRect(50, 710, 81, 21))
        self.exposure_time_label.setObjectName("exposure_time_label")
        self.main_camera_label = QtWidgets.QLabel(self.camera)
        self.main_camera_label.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.main_camera_label.setObjectName("main_camera_label")
        self.exposure_time_bar = QtWidgets.QScrollBar(self.camera)
        self.exposure_time_bar.setGeometry(QtCore.QRect(220, 710, 261, 20))
        self.exposure_time_bar.setAutoFillBackground(False)
        self.exposure_time_bar.setMaximum(100)
        self.exposure_time_bar.setProperty("value", 0)
        self.exposure_time_bar.setTracking(True)
        self.exposure_time_bar.setOrientation(QtCore.Qt.Horizontal)
        self.exposure_time_bar.setInvertedAppearance(False)
        self.exposure_time_bar.setObjectName("exposure_time_bar")
        self.saving_check = QtWidgets.QCheckBox(self.camera)
        self.saving_check.setGeometry(QtCore.QRect(360, 10, 77, 20))
        self.saving_check.setChecked(False)
        self.saving_check.setTristate(False)
        self.saving_check.setObjectName("saving_check")
        self.progress_bar = QtWidgets.QProgressBar(self.camera)
        self.progress_bar.setGeometry(QtCore.QRect(770, 710, 291, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar.sizePolicy().hasHeightForWidth())
        self.progress_bar.setSizePolicy(sizePolicy)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.loading_saving_label = QtWidgets.QLabel(self.camera)
        self.loading_saving_label.setGeometry(QtCore.QRect(710, 699, 51, 31))
        self.loading_saving_label.setObjectName("loading_saving_label")
        self.exposure_time_value = QtWidgets.QLCDNumber(self.camera)
        self.exposure_time_value.setGeometry(QtCore.QRect(150, 710, 64, 23))
        self.exposure_time_value.setFrameShadow(QtWidgets.QFrame.Plain)
        self.exposure_time_value.setSmallDecimalPoint(True)
        self.exposure_time_value.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.exposure_time_value.setObjectName("exposure_time_value")
        self.binning_combo_box = QtWidgets.QComboBox(self.camera)
        self.binning_combo_box.setGeometry(QtCore.QRect(140, 750, 77, 22))
        self.binning_combo_box.setEditable(False)
        self.binning_combo_box.setFrame(True)
        self.binning_combo_box.setObjectName("binning_combo_box")
        self.binning_combo_box.addItem("")
        self.binning_combo_box.addItem("")
        self.binning_combo_box.addItem("")
        self.binning_label = QtWidgets.QLabel(self.camera)
        self.binning_label.setGeometry(QtCore.QRect(70, 743, 52, 31))
        self.binning_label.setObjectName("binning_label")
        self.subArray_mode_radioButton = QtWidgets.QRadioButton(self.camera)
        self.subArray_mode_radioButton.setGeometry(QtCore.QRect(640, 750, 121, 20))
        self.subArray_mode_radioButton.setObjectName("subArray_mode_radioButton")
        self.subarray_label = QtWidgets.QLabel(self.camera)
        self.subarray_label.setGeometry(QtCore.QRect(760, 750, 291, 16))
        self.subarray_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subarray_label.setObjectName("subarray_label")
        self.current_binning_size_label = QtWidgets.QLabel(self.camera)
        self.current_binning_size_label.setGeometry(QtCore.QRect(230, 750, 121, 21))
        self.current_binning_size_label.setObjectName("current_binning_size_label")
        self.current_binning_size_label_2 = QtWidgets.QLabel(self.camera)
        self.current_binning_size_label_2.setGeometry(QtCore.QRect(370, 750, 91, 21))
        self.current_binning_size_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.current_binning_size_label_2.setObjectName("current_binning_size_label_2")
        self.snap_image_button = QtWidgets.QPushButton(self.camera)
        self.snap_image_button.setGeometry(QtCore.QRect(590, 10, 80, 21))
        self.snap_image_button.setObjectName("snap_image_button")
        self.internal_frame_rate_label = QtWidgets.QLabel(self.camera)
        self.internal_frame_rate_label.setGeometry(QtCore.QRect(910, 10, 161, 20))
        self.internal_frame_rate_label.setAlignment(QtCore.Qt.AlignCenter)
        self.internal_frame_rate_label.setObjectName("internal_frame_rate_label")
        self.update_internal_frame_rate_button = QtWidgets.QPushButton(self.camera)
        self.update_internal_frame_rate_button.setGeometry(QtCore.QRect(869, 10, 61, 21))
        self.update_internal_frame_rate_button.setObjectName("update_internal_frame_rate_button")
        self.stop_stream_button = QtWidgets.QPushButton(self.camera)
        self.stop_stream_button.setGeometry(QtCore.QRect(430, 10, 80, 21))
        self.stop_stream_button.setObjectName("stop_stream_button")
        self.folder = QtWidgets.QFrame(self.centralwidget)
        self.folder.setGeometry(QtCore.QRect(10, 20, 1091, 41))
        self.folder.setFrameShape(QtWidgets.QFrame.Box)
        self.folder.setObjectName("folder")
        self.change_folder_button = QtWidgets.QPushButton(self.folder)
        self.change_folder_button.setGeometry(QtCore.QRect(280, 10, 101, 21))
        self.change_folder_button.setObjectName("change_folder_button")
        self.initialize_experiment_button = QtWidgets.QPushButton(self.folder)
        self.initialize_experiment_button.setGeometry(QtCore.QRect(140, 10, 131, 21))
        self.initialize_experiment_button.setObjectName("initialize_experiment_button")
        self.current_folder_label = QtWidgets.QLabel(self.folder)
        self.current_folder_label.setGeometry(QtCore.QRect(390, 10, 91, 21))
        self.current_folder_label.setObjectName("current_folder_label")
        self.current_folder_label_2 = QtWidgets.QLabel(self.folder)
        self.current_folder_label_2.setGeometry(QtCore.QRect(440, 5, 651, 31))
        self.current_folder_label_2.setScaledContents(True)
        self.current_folder_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.current_folder_label_2.setWordWrap(True)
        self.current_folder_label_2.setObjectName("current_folder_label_2")
        self.initialize_hardware_button = QtWidgets.QPushButton(self.folder)
        self.initialize_hardware_button.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.initialize_hardware_button.setObjectName("initialize_hardware_button")
        self.dlp = QtWidgets.QFrame(self.centralwidget)
        self.dlp.setGeometry(QtCore.QRect(1140, 450, 661, 347))
        self.dlp.setFrameShape(QtWidgets.QFrame.Box)
        self.dlp.setObjectName("dlp")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.dlp)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.save_ROI_button = QtWidgets.QPushButton(self.dlp)
        self.save_ROI_button.setObjectName("save_ROI_button")
        self.gridLayout_5.addWidget(self.save_ROI_button, 5, 2, 1, 1)
        self.display_mode_combobox = QtWidgets.QComboBox(self.dlp)
        self.display_mode_combobox.setObjectName("display_mode_combobox")
        self.display_mode_combobox.addItem("")
        self.display_mode_combobox.addItem("")
        self.display_mode_combobox.addItem("")
        self.display_mode_combobox.addItem("")
        self.gridLayout_5.addWidget(self.display_mode_combobox, 2, 0, 1, 2)
        self.saved_ROI_image = Custom_pyqtgraph_widget(self.dlp)
        self.saved_ROI_image.setObjectName("saved_ROI_image")
        self.gridLayout_5.addWidget(self.saved_ROI_image, 0, 2, 5, 2)
        self.display_mode_subbox_combobox = QtWidgets.QComboBox(self.dlp)
        self.display_mode_subbox_combobox.setObjectName("display_mode_subbox_combobox")
        self.gridLayout_5.addWidget(self.display_mode_subbox_combobox, 3, 0, 1, 2)
        self.ROI_label = QtWidgets.QLabel(self.dlp)
        self.ROI_label.setObjectName("ROI_label")
        self.gridLayout_5.addWidget(self.ROI_label, 8, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.ROI_label_placeholder = QtWidgets.QLabel(self.dlp)
        self.ROI_label_placeholder.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ROI_label_placeholder.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ROI_label_placeholder.setScaledContents(True)
        self.ROI_label_placeholder.setWordWrap(True)
        self.ROI_label_placeholder.setObjectName("ROI_label_placeholder")
        self.gridLayout_5.addWidget(self.ROI_label_placeholder, 7, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.dlp_projection_view = QtWidgets.QGraphicsView(self.dlp)
        self.dlp_projection_view.setObjectName("dlp_projection_view")
        self.gridLayout_5.addWidget(self.dlp_projection_view, 4, 0, 5, 2)
        self.reset_ROI_button = QtWidgets.QPushButton(self.dlp)
        self.reset_ROI_button.setObjectName("reset_ROI_button")
        self.gridLayout_5.addWidget(self.reset_ROI_button, 6, 2, 1, 1)
        self.calibration_button = QtWidgets.QPushButton(self.dlp)
        self.calibration_button.setObjectName("calibration_button")
        self.gridLayout_5.addWidget(self.calibration_button, 0, 1, 1, 1)
        self.display_mode_label = QtWidgets.QLabel(self.dlp)
        self.display_mode_label.setScaledContents(True)
        self.display_mode_label.setWordWrap(True)
        self.display_mode_label.setObjectName("display_mode_label")
        self.gridLayout_5.addWidget(self.display_mode_label, 1, 0, 1, 2)
        self.dlp_label = QtWidgets.QLabel(self.dlp)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.dlp_label.setFont(font)
        self.dlp_label.setObjectName("dlp_label")
        self.gridLayout_5.addWidget(self.dlp_label, 0, 0, 1, 1)
        self.laser = QtWidgets.QFrame(self.centralwidget)
        self.laser.setGeometry(QtCore.QRect(1140, 390, 661, 56))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.laser.sizePolicy().hasHeightForWidth())
        self.laser.setSizePolicy(sizePolicy)
        self.laser.setFrameShape(QtWidgets.QFrame.Box)
        self.laser.setObjectName("laser")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.laser)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.laser_label = QtWidgets.QLabel(self.laser)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.laser_label.setFont(font)
        self.laser_label.setObjectName("laser_label")
        self.gridLayout_6.addWidget(self.laser_label, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.laser_off_button = QtWidgets.QPushButton(self.laser)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.laser_off_button.setPalette(palette)
        self.laser_off_button.setCheckable(False)
        self.laser_off_button.setChecked(False)
        self.laser_off_button.setFlat(False)
        self.laser_off_button.setObjectName("laser_off_button")
        self.gridLayout_6.addWidget(self.laser_off_button, 1, 1, 1, 1)
        self.laser_on_button = QtWidgets.QPushButton(self.laser)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.laser_on_button.setPalette(palette)
        self.laser_on_button.setCheckable(False)
        self.laser_on_button.setChecked(False)
        self.laser_on_button.setFlat(False)
        self.laser_on_button.setObjectName("laser_on_button")
        self.gridLayout_6.addWidget(self.laser_on_button, 1, 0, 1, 1)
        self.controls = QtWidgets.QFrame(self.centralwidget)
        self.controls.setGeometry(QtCore.QRect(1140, 120, 661, 251))
        self.controls.setFrameShape(QtWidgets.QFrame.Box)
        self.controls.setObjectName("controls")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.controls)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.y_axis_backward_button = QtWidgets.QPushButton(self.controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_axis_backward_button.sizePolicy().hasHeightForWidth())
        self.y_axis_backward_button.setSizePolicy(sizePolicy)
        self.y_axis_backward_button.setMinimumSize(QtCore.QSize(0, 21))
        self.y_axis_backward_button.setCheckable(False)
        self.y_axis_backward_button.setObjectName("y_axis_backward_button")
        self.gridLayout.addWidget(self.y_axis_backward_button, 3, 0, 1, 2)
        self.y_axis_forward_button = QtWidgets.QPushButton(self.controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_axis_forward_button.sizePolicy().hasHeightForWidth())
        self.y_axis_forward_button.setSizePolicy(sizePolicy)
        self.y_axis_forward_button.setObjectName("y_axis_forward_button")
        self.gridLayout.addWidget(self.y_axis_forward_button, 1, 0, 1, 2)
        self.x_axis_right_button = QtWidgets.QPushButton(self.controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_axis_right_button.sizePolicy().hasHeightForWidth())
        self.x_axis_right_button.setSizePolicy(sizePolicy)
        self.x_axis_right_button.setObjectName("x_axis_right_button")
        self.gridLayout.addWidget(self.x_axis_right_button, 2, 1, 1, 1)
        self.x_axis_left_button = QtWidgets.QPushButton(self.controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_axis_left_button.sizePolicy().hasHeightForWidth())
        self.x_axis_left_button.setSizePolicy(sizePolicy)
        self.x_axis_left_button.setObjectName("x_axis_left_button")
        self.gridLayout.addWidget(self.x_axis_left_button, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.stop_mouvment_button = QtWidgets.QPushButton(self.controls)
        self.stop_mouvment_button.setObjectName("stop_mouvment_button")
        self.gridLayout_7.addWidget(self.stop_mouvment_button, 0, 1, 1, 1)
        self.microscope_control_label = QtWidgets.QLabel(self.controls)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.microscope_control_label.setFont(font)
        self.microscope_control_label.setTextFormat(QtCore.Qt.PlainText)
        self.microscope_control_label.setObjectName("microscope_control_label")
        self.gridLayout_7.addWidget(self.microscope_control_label, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.z_axis_up = QtWidgets.QPushButton(self.controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_axis_up.sizePolicy().hasHeightForWidth())
        self.z_axis_up.setSizePolicy(sizePolicy)
        self.z_axis_up.setObjectName("z_axis_up")
        self.verticalLayout.addWidget(self.z_axis_up)
        self.z_axis_down = QtWidgets.QPushButton(self.controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_axis_down.sizePolicy().hasHeightForWidth())
        self.z_axis_down.setSizePolicy(sizePolicy)
        self.z_axis_down.setObjectName("z_axis_down")
        self.verticalLayout.addWidget(self.z_axis_down)
        self.gridLayout_7.addLayout(self.verticalLayout, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1824, 19))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuMenu.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.binning_combo_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.replay_button.setText(_translate("MainWindow", "Replay"))
        self.stream_button.setText(_translate("MainWindow", "Stream"))
        self.exposure_time_label.setText(_translate("MainWindow", "Exposure time"))
        self.main_camera_label.setText(_translate("MainWindow", "Main Camera"))
        self.saving_check.setText(_translate("MainWindow", "Saving ?"))
        self.loading_saving_label.setText(_translate("MainWindow", "Progress"))
        self.binning_combo_box.setCurrentText(_translate("MainWindow", "1x1"))
        self.binning_combo_box.setItemText(0, _translate("MainWindow", "1x1"))
        self.binning_combo_box.setItemText(1, _translate("MainWindow", "2x2"))
        self.binning_combo_box.setItemText(2, _translate("MainWindow", "4x4"))
        self.binning_label.setText(_translate("MainWindow", "Binning"))
        self.subArray_mode_radioButton.setText(_translate("MainWindow", "SubArray mode"))
        self.subarray_label.setText(_translate("MainWindow", "subarray mode size and origin"))
        self.current_binning_size_label.setText(_translate("MainWindow", "Current binning size"))
        self.current_binning_size_label_2.setText(_translate("MainWindow", "None"))
        self.snap_image_button.setText(_translate("MainWindow", "Snap image"))
        self.internal_frame_rate_label.setText(_translate("MainWindow", "internal frame rate"))
        self.update_internal_frame_rate_button.setText(_translate("MainWindow", "Update "))
        self.stop_stream_button.setText(_translate("MainWindow", "Stop Stream"))
        self.change_folder_button.setText(_translate("MainWindow", "Change Folder"))
        self.initialize_experiment_button.setText(_translate("MainWindow", "Initialize Experiment"))
        self.current_folder_label.setText(_translate("MainWindow", "Current Folder:"))
        self.current_folder_label_2.setText(_translate("MainWindow", "None"))
        self.initialize_hardware_button.setText(_translate("MainWindow", "Initialize Hardware"))
        self.save_ROI_button.setText(_translate("MainWindow", "Save ROI"))
        self.display_mode_combobox.setItemText(0, _translate("MainWindow", "Static Image"))
        self.display_mode_combobox.setItemText(1, _translate("MainWindow", "Internal Test Pattern"))
        self.display_mode_combobox.setItemText(2, _translate("MainWindow", "HDMI Video Input"))
        self.display_mode_combobox.setItemText(3, _translate("MainWindow", "Pattern Sequence Display"))
        self.ROI_label.setText(_translate("MainWindow", "ROI"))
        self.ROI_label_placeholder.setText(_translate("MainWindow", "ROI number saved"))
        self.reset_ROI_button.setText(_translate("MainWindow", "Reset ROI"))
        self.calibration_button.setToolTip(_translate("MainWindow", "<html><head/><body><p>Calibrate the DLP/Camera images with their respective resolutions so that ROI designed from the camera interface can be projected with the DLP </p></body></html>"))
        self.calibration_button.setText(_translate("MainWindow", "Calibration"))
        self.display_mode_label.setText(_translate("MainWindow", "Current Display Mode"))
        self.dlp_label.setText(_translate("MainWindow", "DLP"))
        self.laser_label.setText(_translate("MainWindow", "Laser"))
        self.laser_off_button.setText(_translate("MainWindow", "Laser_off_buton"))
        self.laser_on_button.setText(_translate("MainWindow", "Laser_on_buton"))
        self.y_axis_backward_button.setText(_translate("MainWindow", "Y Axis BACKWARD"))
        self.y_axis_forward_button.setText(_translate("MainWindow", "Y axis FORWARD"))
        self.x_axis_right_button.setText(_translate("MainWindow", "X axis RIGHT"))
        self.x_axis_left_button.setText(_translate("MainWindow", "X axis LEFT"))
        self.stop_mouvment_button.setText(_translate("MainWindow", "STOP"))
        self.microscope_control_label.setText(_translate("MainWindow", "Microscope control"))
        self.z_axis_up.setText(_translate("MainWindow", "Z axis UP"))
        self.z_axis_down.setText(_translate("MainWindow", "Z axis DOWN"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

from custom_pyqtgraph_widget import Custom_pyqtgraph_widget
